### PR TITLE
test accesslint

### PR DESCRIPTION
**Pull request by leonstafford**
see if it catches something simple

### CODE REVIEW

**Comment by leonstafford** [comment]
Stuck for 7 mins now, waiting for AccessLint to check my commits

Now have 2 commits stuck for 7 mins without review from AccessLint... not sure what logic/rate limiting they may be applying or if the linting service is just having issues... but another reason to use your own/locally install tools for automated linting

**Comment by rkingett** [comment]
Good bot. Give it a cookie. Still, I wish there was something a bit better. This will do for sites like Bookwyrm though, I am sure.

**Comment by ckundo** [comment]
Hi folks, I'm the founder of AccessLint, here at the bequest of @leonstafford! Digging into why that review didn't finish now. I'll follow up with notes.

**Comment by ckundo** [comment]
@leonstafford would you mind syncing the PR by pushing an empty commit? `git commit --allow-empty -m"sync"`

**Comment by leonstafford** [comment]
Thanks, @ckundo! Just stepped away from PC, will submit once back.

**Comment by ckundo** [comment]
@leonstafford thanks... still digging!

**Comment by ckundo** [comment]
I'm a little stumped at the moment, but will continue to look into it. Sorry about that; you can try closing and reopening the PR to dismiss the stale status...

**Comment by ckundo** [comment]
actually, if you wouldn't mind terribly, leave it open so I can debug more. thanks!

**Comment by leonstafford** [comment]
Yep, not a problem, thanks!

**Comment by ckundo** [comment]
ah, found the issue. thank you for your patience!

**Comment by rkingett** [comment]
Looks like the bot is doing good now! :)

**Pull request merged**
